substitutions:
  _BUILD_DIR: build-output
  _PROJECT_STAGING: ai-autonomous-coder-staging
  _PROJECT_PRODUCTION: ai-autonomous-coder-prod
  _PRODUCTION_APPROVED: "false"
  _FIREBASE_CHANNEL: staging

steps:
  - id: Install dependencies
    name: gcr.io/cloud-builders/npm
    env:
      - NPM_CONFIG_CACHE=/workspace/.npm
    args: ["ci"]

  - id: Build
    name: gcr.io/cloud-builders/npm
    env:
      - NPM_CONFIG_CACHE=/workspace/.npm
    args: ["run", "build"]

  - id: Test
    name: gcr.io/cloud-builders/npm
    env:
      - NPM_CONFIG_CACHE=/workspace/.npm
    args: ["test"]

  - id: Lint
    name: gcr.io/cloud-builders/npm
    env:
      - NPM_CONFIG_CACHE=/workspace/.npm
    args: ["run", "lint"]

  - id: Prepare deployable artifact
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        BUILD_DIR="${_BUILD_DIR}"
        rm -rf "${BUILD_DIR}"
        mkdir -p "${BUILD_DIR}"
        shopt -s dotglob extglob nullglob
        cp -r !(node_modules|.git|.github|${BUILD_DIR}) "${BUILD_DIR}/"

  - id: Install Firebase CLI
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    env:
      - NPM_CONFIG_CACHE=/workspace/.npm
    args:
      - -c
      - |
        set -euo pipefail
        npm config set prefix /workspace/.npm-global
        npm install -g firebase-tools

  - id: Deploy to staging channel
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    secretEnv:
      - FIREBASE_TOKEN_STAGING
    args:
      - -c
      - |
        set -euo pipefail
        export PATH="/workspace/.npm-global/bin:${PATH}"
        cd "${_BUILD_DIR}"
        firebase hosting:channel:deploy "${_FIREBASE_CHANNEL}" \
          --project "${_PROJECT_STAGING}" \
          --token "${FIREBASE_TOKEN_STAGING}" \
          --config ../firebase.json \
          --force

  - id: Deploy to production
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    secretEnv:
      - FIREBASE_TOKEN_PRODUCTION
    args:
      - -c
      - |
        set -euo pipefail
        if [[ "${_PRODUCTION_APPROVED}" != "true" ]]; then
          echo "Production deployment skipped until manual approval. Re-run with _PRODUCTION_APPROVED=true after approval."
          exit 0
        fi
        export PATH="/workspace/.npm-global/bin:${PATH}"
        cd "${_BUILD_DIR}"
        firebase deploy \
          --only hosting \
          --project "${_PROJECT_PRODUCTION}" \
          --token "${FIREBASE_TOKEN_PRODUCTION}" \
          --config ../firebase.json \
          --non-interactive

artifacts:
  objects:
    location: gs://$PROJECT_ID-build-artifacts/$BUILD_ID/
    paths:
      - ${_BUILD_DIR}/**/*

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN_STAGING/versions/latest
      env: FIREBASE_TOKEN_STAGING
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN_PRODUCTION/versions/latest
      env: FIREBASE_TOKEN_PRODUCTION

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

caches:
  - id: npm-cache
    path: /workspace/.npm
  - id: firebase-cache
    path: /workspace/.cache/firebase
